var GITHUB_PAGES_BASE = '/Portfolio-Store-for-Sell-Project/';
function githubProjectUrl(path) {
  var clean = String(path || '')
    .replace(/^(?:\.\.\/)+/, '')
    .replace(/^\/+/, '');
  return GITHUB_PAGES_BASE + clean;
}

window.PORTFOLIO = {
  youtubeUrl: 'https://www.youtube.com/@CodeWithMoaaz',
  facebookUrl: '',
  whatsappUrl: 'https://wa.me/201097446721',
  projects: [
    {slug:'barber-website',path:'Barbur Website/index.html',name:{en:'Barbur Website',ar:'Barbur Website'},desc:{en:'A sharp, editorial barber experience with cinematic detail.',ar:'تجربة حلاقة عصرية بطابع تحريري وتفاصيل سينمائية.'},cat:{en:'Beauty & Grooming',ar:'الجمال والعناية'},tags:['barber','salon','grooming','حلاق','حلاقة','صالون','html','css','javascript'],cover:'assets/covers/barber-website.webp',download:'downloads/Barbur Website.zip'},
    {slug:'clothing-store',path:'Clothing Store Website/index.html',name:{en:'Clothing Store Website',ar:'Clothing Store Website'},desc:{en:'A luxury fashion storefront built around quiet confidence.',ar:'متجر أزياء فاخر مبني على أناقة هادئة وحضور قوي.'},cat:{en:'Fashion',ar:'أزياء'},tags:['fashion','clothing','store','ecommerce','ملابس','أزياء','متجر'],cover:'assets/covers/clothing-store.webp',download:'downloads/Clothing Store Website.zip'},
    {slug:'coffee-website',path:'Coffe Website/index.html',name:{en:'Coffe Website',ar:'Coffe Website'},desc:{en:'A warm specialty coffee world with tactile visual rhythm.',ar:'عالم قهوة دافئ بإيقاع بصري حسي ومميز.'},cat:{en:'Food & Beverage',ar:'أغذية ومشروبات'},tags:['coffee','cafe','café','restaurant','قهوة','كافيه','مقهى'],cover:'assets/covers/coffee-website.webp',download:'downloads/Coffe Website.zip'},
    {slug:'dental-clinic',path:'Dental Clinic Website/index.html',name:{en:'Dental Clinic Website',ar:'Dental Clinic Website'},desc:{en:'A calm, trustworthy healthcare interface for modern dentistry.',ar:'واجهة صحية هادئة وموثوقة لعيادة أسنان عصرية.'},cat:{en:'Healthcare',ar:'رعاية صحية'},tags:['dentist','dental','clinic','health','أسنان','طبيب','عيادة'],cover:'assets/covers/dental-clinic.webp',download:'downloads/Dental Clinic Website.zip'},
    {slug:'fitness-website',path:'Fitness Website/index.html',name:{en:'Fitness Website',ar:'Fitness Website'},desc:{en:'An energetic performance-focused fitness experience.',ar:'تجربة لياقة بدنية ديناميكية تركز على الأداء.'},cat:{en:'Fitness',ar:'لياقة'},tags:['fitness','gym','training','workout','جيم','رياضة','تمرين','لياقة'],cover:'assets/covers/fitness-website.webp',download:'downloads/Fitness Website.zip'},
    {slug:'hospital-website',path:'Hospital Website/index.html',name:{en:'Hospital Website',ar:'Hospital Website'},desc:{en:'A contemporary hospital interface balancing clarity and care.',ar:'واجهة مستشفى عصرية تجمع بين الوضوح والاهتمام.'},cat:{en:'Healthcare',ar:'رعاية صحية'},tags:['hospital','doctor','medical','healthcare','مستشفى','طبيب','طب'],cover:'assets/covers/hospital-website.webp',download:'downloads/Hospital Website.zip'},
    {slug:'hotel-website',path:'Hotel Website/index.html',name:{en:'Hotel Website',ar:'Hotel Website'},desc:{en:'A refined hospitality experience designed like a boutique stay.',ar:'تجربة ضيافة راقية مصممة بروح فندق بوتيك.'},cat:{en:'Hospitality',ar:'ضيافة'},tags:['hotel','resort','travel','luxury','فندق','منتجع','سفر','فاخر'],cover:'assets/covers/hotel-website.webp',download:'downloads/Hotel Website.zip'},
    {slug:'luxury-interior-design',path:'Luxury Interior Design Website/index.html',name:{en:'Luxury Interior Design Website',ar:'Luxury Interior Design Website'},desc:{en:'A sculptural interior design experience with quiet luxury.',ar:'تجربة تصميم داخلي منحوتة بروح الفخامة الهادئة.'},cat:{en:'Interior Design',ar:'تصميم داخلي'},tags:['interior','architecture','design','ديكور','تصميم','هندسة'],cover:'assets/covers/luxury-interior-design.webp',download:'downloads/Luxury Interior Design Website.zip'},
    {slug:'luxury-jewelry',path:'Luxury Jewelry Website/index.html',name:{en:'Luxury Jewelry Website',ar:'Luxury Jewelry Website'},desc:{en:'A jewelry identity built around light, form and precious detail.',ar:'هوية مجوهرات مبنية حول الضوء والشكل والتفاصيل الثمينة.'},cat:{en:'Jewelry',ar:'مجوهرات'},tags:['jewelry','luxury','gold','rings','مجوهرات','ذهب','خواتم'],cover:'assets/covers/luxury-jewelry.webp',download:'downloads/Luxury Jewelry Website.zip'},
    {slug:'cars-store-website',path:'Cars Store Website/index.html',name:{en:'Cars Store Website',ar:'Cars Store Website'},desc:{en:'A performance automotive experience with engineered tension.',ar:'تجربة سيارات رياضية بإيقاع بصري حاد ودقيق.'},cat:{en:'Automotive',ar:'سيارات'},tags:['cars','automotive','motors','supercar','سيارات','عربيات','محركات','رياضي'],cover:'assets/covers/motif-motors.webp',download:'downloads/Cars Store Website.zip'},
    {slug:'north-and-co',path:'NORTH & CO Website/index.html',name:{en:'NORTH & CO Website',ar:'NORTH & CO Website'},desc:{en:'A confident professional identity for a modern law firm.',ar:'هوية مهنية واثقة لمكتب قانون عصري.'},cat:{en:'Professional',ar:'مهني'},tags:['law','lawyer','legal','business','محاماة','قانون','شركة'],cover:'assets/covers/north-and-co.webp',download:'downloads/NORTH & CO Website.zip'},
    {slug:'photography-studio',path:'Photography Studio Website/index.html',name:{en:'Photography Studio Website',ar:'Photography Studio Website'},desc:{en:'A visual-first photography portfolio with gallery energy.',ar:'محفظة تصوير بصرية أولًا بطاقة معرض فني.'},cat:{en:'Photography',ar:'تصوير'},tags:['photography','studio','photo','تصوير','استوديو','صور'],cover:'assets/covers/photography-studio.webp',download:'downloads/Photography Studio Website.zip'},
    {slug:'real-estate',path:'Real Estate Website/index.html',name:{en:'Real Estate Website',ar:'Real Estate Website'},desc:{en:'A premium real-estate presentation focused on place and space.',ar:'عرض عقاري فاخر يركز على المكان والمساحة.'},cat:{en:'Real Estate',ar:'عقارات'},tags:['real estate','property','villa','house','عقارات','منازل','فلل','ممتلكات'],cover:'assets/covers/real-estate.webp',download:'downloads/Real Estate Website.zip'},
    {slug:'restaurant',path:'Restaurent WebSite/index.html',name:{en:'Restaurent WebSite',ar:'Restaurent WebSite'},desc:{en:'A rich restaurant experience built around appetite and atmosphere.',ar:'تجربة مطعم غنية تدور حول الشهية والأجواء.'},cat:{en:'Restaurant',ar:'مطعم'},tags:['restaurant','food','dining','مطعم','أكل','طعام','وجبات'],cover:'assets/covers/restaurant.webp',download:'downloads/Restaurent WebSite.zip'},
    {slug:'wander-travel',path:'Wander Travel Website/index.html',name:{en:'Wander Travel Website',ar:'Wander Travel Website'},desc:{en:'A travel journal that makes distant places feel close.',ar:'مجلة سفر تجعل الأماكن البعيدة تبدو قريبة.'},cat:{en:'Travel',ar:'سفر'},tags:['travel','tourism','journey','trip','سفر','سياحة','رحلات','مغامرة'],cover:'assets/covers/wander-travel.webp',download:'downloads/Wander Travel Website.zip'}
  ]
};
