
const money = n => `$${n.toLocaleString()}`;
const getWishlist=()=>JSON.parse(localStorage.getItem('aurelia-wishlist')||'[]');
const setWishlist=x=>localStorage.setItem('aurelia-wishlist',JSON.stringify(x));
function toast(msg){let t=document.querySelector('.toast'); if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function updateCount(){const c=document.querySelector('.count');if(c)c.textContent=getWishlist().length}
function toggleWish(id,el){let w=getWishlist(); if(w.includes(id)){w=w.filter(x=>x!==id);el?.classList.remove('active');toast('Removed from wishlist')}else{w.push(id);el?.classList.add('active');toast('Added to wishlist')}setWishlist(w);updateCount()}
function productCard(p){const w=getWishlist().includes(p.id);return `<article class="product"><div class="product-img"><img src="${p.image}" alt="${p.name}" loading="lazy"><button class="wish ${w?'active':''}" aria-label="wishlist" onclick="toggleWish(${p.id},this)">♡</button></div><div class="product-info"><h3>${p.name}</h3><p>${p.category} · Fine Jewelry</p><span class="price">${money(p.price)}</span></div></article>`}
function renderShop(filter='All Jewelry'){const grid=document.querySelector('#products');if(!grid)return;let list=filter==='All Jewelry'?PRODUCTS:PRODUCTS.filter(p=>p.category===filter);grid.innerHTML=list.map(productCard).join('');const title=document.querySelector('#shop-count');if(title)title.textContent=`${list.length} pieces`}
function initShop(){let params=new URLSearchParams(location.search);let cat=params.get('category')||'All Jewelry';document.querySelectorAll('[data-cat]').forEach(b=>{b.classList.toggle('active',b.dataset.cat===cat);b.onclick=()=>{history.replaceState({},'',`shop.html?category=${encodeURIComponent(b.dataset.cat)}`);document.querySelectorAll('[data-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderShop(b.dataset.cat)}});renderShop(cat)}
function initWishlist(){const grid=document.querySelector('#wishlist-grid');if(!grid)return;let list=PRODUCTS.filter(p=>getWishlist().includes(p.id));grid.innerHTML=list.length?list.map(productCard).join(''):`<div class="empty" style="grid-column:1/-1"><h2>Your wishlist is waiting.</h2><p class="lead" style="margin:10px auto 25px">Save pieces you love and keep them close.</p><a class="btn" href="shop.html">Explore Jewelry →</a></div>`}
function init(){document.querySelectorAll('.menu-btn').forEach(b=>b.onclick=()=>document.querySelector('.nav-links').classList.toggle('open'));document.querySelectorAll('form[data-demo]').forEach(f=>f.onsubmit=e=>{e.preventDefault();toast('Thank you — your message has been received.');f.reset()});updateCount();initShop();initWishlist()}
document.addEventListener('DOMContentLoaded',init);
